/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardCampaignsIndexRouteImport } from './routes/dashboard/campaigns/index'
import { Route as DashboardCampaignsCampaignIdRouteImport } from './routes/dashboard/campaigns/$campaignId'
import { Route as DashboardCampaignsNewRouteImport } from './routes/dashboard/campaigns/new'
import { Route as DashboardLeadsIndexRouteImport } from './routes/dashboard/leads/index'
import { Route as DashboardLeadsLeadIdRouteImport } from './routes/dashboard/leads/$leadId'
import { Route as DashboardLeadsImportRouteImport } from './routes/dashboard/leads/import'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardTemplatesNewRouteImport } from './routes/dashboard/templates/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCampaignsIndexRoute = DashboardCampaignsIndexRouteImport.update({
  id: '/dashboard/campaigns/',
  path: '/dashboard/campaigns/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCampaignsCampaignIdRoute =
  DashboardCampaignsCampaignIdRouteImport.update({
    id: '/dashboard/campaigns/$campaignId',
    path: '/dashboard/campaigns/$campaignId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardCampaignsNewRoute = DashboardCampaignsNewRouteImport.update({
  id: '/dashboard/campaigns/new',
  path: '/dashboard/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsIndexRoute = DashboardLeadsIndexRouteImport.update({
  id: '/dashboard/leads/',
  path: '/dashboard/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsLeadIdRoute = DashboardLeadsLeadIdRouteImport.update({
  id: '/dashboard/leads/$leadId',
  path: '/dashboard/leads/$leadId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLeadsImportRoute = DashboardLeadsImportRouteImport.update({
  id: '/dashboard/leads/import',
  path: '/dashboard/leads/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/dashboard/templates/',
  path: '/dashboard/templates/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesNewRoute = DashboardTemplatesNewRouteImport.update({
  id: '/dashboard/templates/new',
  path: '/dashboard/templates/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/campaigns/new': typeof DashboardCampaignsNewRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/leads/import': typeof DashboardLeadsImportRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/campaigns/new': typeof DashboardCampaignsNewRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/leads/import': typeof DashboardLeadsImportRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/campaigns': typeof DashboardCampaignsIndexRoute
  '/dashboard/leads': typeof DashboardLeadsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/campaigns/$campaignId': typeof DashboardCampaignsCampaignIdRoute
  '/dashboard/campaigns/new': typeof DashboardCampaignsNewRoute
  '/dashboard/leads/$leadId': typeof DashboardLeadsLeadIdRoute
  '/dashboard/leads/import': typeof DashboardLeadsImportRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/campaigns/': typeof DashboardCampaignsIndexRoute
  '/dashboard/leads/': typeof DashboardLeadsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/campaigns/new'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/import'
    | '/dashboard/templates/new'
    | '/dashboard/campaigns/'
    | '/dashboard/leads/'
    | '/dashboard/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/campaigns/new'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/import'
    | '/dashboard/templates/new'
    | '/dashboard/campaigns'
    | '/dashboard/leads'
    | '/dashboard/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/dashboard/campaigns/$campaignId'
    | '/dashboard/campaigns/new'
    | '/dashboard/leads/$leadId'
    | '/dashboard/leads/import'
    | '/dashboard/templates/new'
    | '/dashboard/campaigns/'
    | '/dashboard/leads/'
    | '/dashboard/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCampaignsCampaignIdRoute: typeof DashboardCampaignsCampaignIdRoute
  DashboardCampaignsNewRoute: typeof DashboardCampaignsNewRoute
  DashboardLeadsLeadIdRoute: typeof DashboardLeadsLeadIdRoute
  DashboardLeadsImportRoute: typeof DashboardLeadsImportRoute
  DashboardTemplatesNewRoute: typeof DashboardTemplatesNewRoute
  DashboardCampaignsIndexRoute: typeof DashboardCampaignsIndexRoute
  DashboardLeadsIndexRoute: typeof DashboardLeadsIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaigns/': {
      id: '/dashboard/campaigns/'
      path: '/dashboard/campaigns'
      fullPath: '/dashboard/campaigns/'
      preLoaderRoute: typeof DashboardCampaignsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaigns/$campaignId': {
      id: '/dashboard/campaigns/$campaignId'
      path: '/dashboard/campaigns/$campaignId'
      fullPath: '/dashboard/campaigns/$campaignId'
      preLoaderRoute: typeof DashboardCampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/campaigns/new': {
      id: '/dashboard/campaigns/new'
      path: '/dashboard/campaigns/new'
      fullPath: '/dashboard/campaigns/new'
      preLoaderRoute: typeof DashboardCampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/': {
      id: '/dashboard/leads/'
      path: '/dashboard/leads'
      fullPath: '/dashboard/leads/'
      preLoaderRoute: typeof DashboardLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/$leadId': {
      id: '/dashboard/leads/$leadId'
      path: '/dashboard/leads/$leadId'
      fullPath: '/dashboard/leads/$leadId'
      preLoaderRoute: typeof DashboardLeadsLeadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/leads/import': {
      id: '/dashboard/leads/import'
      path: '/dashboard/leads/import'
      fullPath: '/dashboard/leads/import'
      preLoaderRoute: typeof DashboardLeadsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/dashboard/templates'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates/new': {
      id: '/dashboard/templates/new'
      path: '/dashboard/templates/new'
      fullPath: '/dashboard/templates/new'
      preLoaderRoute: typeof DashboardTemplatesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCampaignsCampaignIdRoute: DashboardCampaignsCampaignIdRoute,
  DashboardCampaignsNewRoute: DashboardCampaignsNewRoute,
  DashboardLeadsLeadIdRoute: DashboardLeadsLeadIdRoute,
  DashboardLeadsImportRoute: DashboardLeadsImportRoute,
  DashboardTemplatesNewRoute: DashboardTemplatesNewRoute,
  DashboardCampaignsIndexRoute: DashboardCampaignsIndexRoute,
  DashboardLeadsIndexRoute: DashboardLeadsIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
