/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthErrorRouteImport } from './routes/auth.error'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardMailsIndexRouteImport } from './routes/dashboard/mails/index'
import { Route as DashboardMailsNewRouteImport } from './routes/dashboard/mails/new'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardTemplatesNewRouteImport } from './routes/dashboard/templates/new'
import { Route as DashboardEmailHistoryEmailIdStatsRouteImport } from './routes/dashboard/email-history/$emailId.stats'
import { Route as DashboardTemplatesTemplateIdEditRouteImport } from './routes/dashboard/templates/$templateId.edit'
import { Route as DashboardTemplatesTemplateIdStatsRouteImport } from './routes/dashboard/templates/$templateId.stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailsIndexRoute = DashboardMailsIndexRouteImport.update({
  id: '/mails/',
  path: '/mails/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMailsNewRoute = DashboardMailsNewRouteImport.update({
  id: '/mails/new',
  path: '/mails/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesNewRoute = DashboardTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmailHistoryEmailIdStatsRoute =
  DashboardEmailHistoryEmailIdStatsRouteImport.update({
    id: '/email-history/$emailId/stats',
    path: '/email-history/$emailId/stats',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTemplatesTemplateIdEditRoute =
  DashboardTemplatesTemplateIdEditRouteImport.update({
    id: '/templates/$templateId/edit',
    path: '/templates/$templateId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTemplatesTemplateIdStatsRoute =
  DashboardTemplatesTemplateIdStatsRouteImport.update({
    id: '/templates/$templateId/stats',
    path: '/templates/$templateId/stats',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/mails/new': typeof DashboardMailsNewRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/mails/': typeof DashboardMailsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/email-history/$emailId/stats': typeof DashboardEmailHistoryEmailIdStatsRoute
  '/dashboard/templates/$templateId/edit': typeof DashboardTemplatesTemplateIdEditRoute
  '/dashboard/templates/$templateId/stats': typeof DashboardTemplatesTemplateIdStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/mails/new': typeof DashboardMailsNewRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/mails': typeof DashboardMailsIndexRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
  '/dashboard/email-history/$emailId/stats': typeof DashboardEmailHistoryEmailIdStatsRoute
  '/dashboard/templates/$templateId/edit': typeof DashboardTemplatesTemplateIdEditRoute
  '/dashboard/templates/$templateId/stats': typeof DashboardTemplatesTemplateIdStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/auth/error': typeof AuthErrorRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/mails/new': typeof DashboardMailsNewRoute
  '/dashboard/templates/new': typeof DashboardTemplatesNewRoute
  '/dashboard/mails/': typeof DashboardMailsIndexRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
  '/dashboard/email-history/$emailId/stats': typeof DashboardEmailHistoryEmailIdStatsRoute
  '/dashboard/templates/$templateId/edit': typeof DashboardTemplatesTemplateIdEditRoute
  '/dashboard/templates/$templateId/stats': typeof DashboardTemplatesTemplateIdStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/auth/error'
    | '/dashboard/'
    | '/dashboard/mails/new'
    | '/dashboard/templates/new'
    | '/dashboard/mails/'
    | '/dashboard/settings/'
    | '/dashboard/templates/'
    | '/dashboard/email-history/$emailId/stats'
    | '/dashboard/templates/$templateId/edit'
    | '/dashboard/templates/$templateId/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/auth/error'
    | '/dashboard'
    | '/dashboard/mails/new'
    | '/dashboard/templates/new'
    | '/dashboard/mails'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/email-history/$emailId/stats'
    | '/dashboard/templates/$templateId/edit'
    | '/dashboard/templates/$templateId/stats'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/terms'
    | '/verify-email'
    | '/auth/error'
    | '/dashboard/'
    | '/dashboard/mails/new'
    | '/dashboard/templates/new'
    | '/dashboard/mails/'
    | '/dashboard/settings/'
    | '/dashboard/templates/'
    | '/dashboard/email-history/$emailId/stats'
    | '/dashboard/templates/$templateId/edit'
    | '/dashboard/templates/$templateId/stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthErrorRoute: typeof AuthErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mails/': {
      id: '/dashboard/mails/'
      path: '/mails'
      fullPath: '/dashboard/mails/'
      preLoaderRoute: typeof DashboardMailsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/mails/new': {
      id: '/dashboard/mails/new'
      path: '/mails/new'
      fullPath: '/dashboard/mails/new'
      preLoaderRoute: typeof DashboardMailsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/settings'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/new': {
      id: '/dashboard/templates/new'
      path: '/templates/new'
      fullPath: '/dashboard/templates/new'
      preLoaderRoute: typeof DashboardTemplatesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/email-history/$emailId/stats': {
      id: '/dashboard/email-history/$emailId/stats'
      path: '/email-history/$emailId/stats'
      fullPath: '/dashboard/email-history/$emailId/stats'
      preLoaderRoute: typeof DashboardEmailHistoryEmailIdStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/$templateId/edit': {
      id: '/dashboard/templates/$templateId/edit'
      path: '/templates/$templateId/edit'
      fullPath: '/dashboard/templates/$templateId/edit'
      preLoaderRoute: typeof DashboardTemplatesTemplateIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/templates/$templateId/stats': {
      id: '/dashboard/templates/$templateId/stats'
      path: '/templates/$templateId/stats'
      fullPath: '/dashboard/templates/$templateId/stats'
      preLoaderRoute: typeof DashboardTemplatesTemplateIdStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardMailsNewRoute: typeof DashboardMailsNewRoute
  DashboardTemplatesNewRoute: typeof DashboardTemplatesNewRoute
  DashboardMailsIndexRoute: typeof DashboardMailsIndexRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
  DashboardEmailHistoryEmailIdStatsRoute: typeof DashboardEmailHistoryEmailIdStatsRoute
  DashboardTemplatesTemplateIdEditRoute: typeof DashboardTemplatesTemplateIdEditRoute
  DashboardTemplatesTemplateIdStatsRoute: typeof DashboardTemplatesTemplateIdStatsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardMailsNewRoute: DashboardMailsNewRoute,
  DashboardTemplatesNewRoute: DashboardTemplatesNewRoute,
  DashboardMailsIndexRoute: DashboardMailsIndexRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
  DashboardEmailHistoryEmailIdStatsRoute:
    DashboardEmailHistoryEmailIdStatsRoute,
  DashboardTemplatesTemplateIdEditRoute: DashboardTemplatesTemplateIdEditRoute,
  DashboardTemplatesTemplateIdStatsRoute:
    DashboardTemplatesTemplateIdStatsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthErrorRoute: AuthErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
